bedrock:
  address: 0.0.0.0
  port: 19132

java:
  address: baystellardynasty.aternos.me
  port: 45295
  auth-type: offline

motd:
  primary-motd: Geyser
  secondary-motd: Another Geyser server.
  passthrough-motd: true

gameplay:
  show-coordinates: true

config-version: 8
